#!/usr/bin/env python
# -*- coding: utf-8 -*-
from pathlib import Path
import argparse
from Bio import SeqIO


# ===================== TODO: Scoring matrix init =========================================

def init_score_matrix_global(m: int, n: int, gap: int):
    # matrice (m+1) x (n+1) cu 0
    score = [[0] * (n + 1) for _ in range(m + 1)]
    # prima coloană: i * gap
    for i in range(1, m + 1):
        score[i][0] = score[i - 1][0] + gap
    # prima linie: j * gap
    for j in range(1, n + 1):
        score[0][j] = score[0][j - 1] + gap
    return score



def score_cell_global(score, i: int, j: int, a: str, b: str, match: int, mismatch: int, gap: int):
    diag  = score[i - 1][j - 1] + (match if a == b else mismatch)
    up    = score[i - 1][j] + gap
    left  = score[i][j - 1] + gap
    return max(diag, up, left)



def needleman_wunsch(seq1: str, seq2: str, match=1, mismatch=-1, gap=-2):
    # Implementare simplificată Needleman–Wunsch.
    m, n = len(seq1), len(seq2)

    # Inițializare matrice (voi completați funcția)
    score = init_score_matrix_global(m, n, gap)

    # Umplem matricea celulă cu celulă
    # Observație: buclele merg de la 1 la lungimea secvenței
    for i in range(1, m + 1):
        ai = seq1[i - 1]
        for j in range(1, n + 1):
            bj = seq2[j - 1]
            # apelăm funcția pentru scor
            score[i][j] = score_cell_global(score, i, j, ai, bj, match, mismatch, gap)

    # ================== Backtracking ==================
    # pornim din colțul dreapta-jos (scor[m][n])
    align1, align2 = "", ""
    i, j = m, n
    while i > 0 and j > 0:
        current = score[i][j]
        # recalculăm scorurile vecinilor pentru a decide de unde am venit
        diag = score[i - 1][j - 1] + (match if seq1[i - 1] == seq2[j - 1] else mismatch)
        up   = score[i - 1][j] + gap
        left = score[i][j - 1] + gap

        if current == diag:  # am venit pe diagonală
            align1 = seq1[i - 1] + align1
            align2 = seq2[j - 1] + align2
            i -= 1; j -= 1
        elif current == up:  # am venit de sus
            align1 = seq1[i - 1] + align1
            align2 = "-" + align2
            i -= 1
        else:                # am venit de la stânga
            align1 = "-" + align1
            align2 = seq2[j - 1] + align2
            j -= 1

    # dacă am ajuns la margine, completăm cu gap-uri
    while i > 0:
        align1 = seq1[i - 1] + align1
        align2 = "-" + align2
        i -= 1
    while j > 0:
        align1 = "-" + align1
        align2 = seq2[j - 1] + align2
        j -= 1

    return align1, align2, score[m][n]


def load_two_sequences(fasta_path: Path, i1: int, i2: int):
    """
    Încărcăm FASTA și alegem două secvențe după index.
    """
    recs = list(SeqIO.parse(str(fasta_path), "fasta"))
    if len(recs) < 2:
        raise SystemExit("[eroare] Fișierul trebuie să conțină cel puțin 2 secvențe.")
    if not (0 <= i1 < len(recs) and 0 <= i2 < len(recs)):
        raise SystemExit(f"[eroare] Indici invalizi (0..{len(recs)-1}).")
    return str(recs[i1].seq), str(recs[i2].seq), recs[i1].id, recs[i2].id


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fasta", required=True, help="Cale către FASTA-ul propriu din data/work/<handle>/lab01/")
    ap.add_argument("--i1", type=int, default=0, help="Index prima secvență (implicit 0)")
    ap.add_argument("--i2", type=int, default=1, help="Index a doua secvență (implicit 1)")
    args = ap.parse_args()

    fasta_path = Path(args.fasta)
    if not fasta_path.exists():
        raise SystemExit(f"[eroare] Nu găsesc fișierul: {fasta_path}")

    s1, s2, id1, id2 = load_two_sequences(fasta_path, args.i1, args.i2)
    a1, a2, sc = needleman_wunsch(s1, s2)

    print("=== Aliniere globală (NW) ===")
    print(f"{id1}  vs  {id2}")
    print(a1)
    print(a2)
    print("Score:", sc)


if __name__ == "__main__":
    main()

"""

=== Aliniere globală (NW) ===
NG_017013.2  vs  NC_060941.1
CTCCTTGGTTCAAGTAATTCTCCTGCCTCAGACTCCAGAGTAGCTGGGATTACAGGCGCCCGCCACCACGCCCAGCTAATTTTTTGTATTTTTAATAGAGATGGGGTTTCATCATGTTGGCCAGGCTGGTCTCGAACTCCTGACCTCAGGTGATCCACCTGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGAGTCAGCCACCGCACCCAGCCCCAA-CTAATTTTTGTATTTGAGTAGAGACAGGGTTTTACCATGTTGGCCAGGCTGGTCTAAAACTCTTCACCTCAGGTGATCC-ACCCATCTCAGCCTCCCAAAGTGTTGGGATTACAGGCGTGAGCCACCGTGCCTGGCCCTGGATTTCACTCTTGCCC-ACCCATAAACCATTCACTCTTCTGTTTTAAAACTCTCTTGGCCGGGCGCAGTGGCTCATGCCTGTAATCCCAGCACTTTGGGAGGCCAAGGTGGGCAGATCACAAGGTCAGGAGTTCGAGACCAGCCTGGCCAATATGATGAACCCCCCATCTCTACTAAAAAAATACAAAAAAATTAGCCGGGTGTGGTGGCACATGCCTGTAATCCCAGCTACTCGGAAGGTTGAGGCAGGAGAATCACTTAAACCTGGGAGGCGGAGGTTGCGGTGAGCTGAGATGGTGCCACTGCACTCCAGCCTGGACAACAGAGCAAGACTCTGTCTCAAACAAACAAACAAAAAAAACCTCTCTCATGGCCTGGCATGGTGGCTCACGCCTGTAATCCTAGCACTTTGGAAGGCTGAGGCAGGTGGATCACCTGAGGTCAGGAGTTTGAGACCAGCCAGGCC-AACGTGGCAAAACCTGTCTCTACTAAAAATACAAAAATTAAGCCAGGCGCGGTGGCTCATGCCTATAATCCCAGCACTTTGGGAGGCCGAGACCGGCGGATCAAATGTCAGGAGTACGAGACCATCCTGGCCAATATGGTAAAACCCCGTCTCTATTTAAAAAAATACAAAAATTAGCTGGGCATGGTGGCGGGTGCCTGTAATCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATCGCTTGAATCCAGGAGGCAGAGGTTGCAGTGAGCCGAGATCACGCCATTGCACTCCAGCCTGGGCGACAGAGCAAGACTCGTCTCAAAAAAAAAAAAAAAACACCTCTCTCATGACTTCCCAAATAAACTCCAAATGCCTTACCCATAAGAACCAACACGACGTGGCTGCTCTTCTCTGTCCTCACCCCTCTGTCCCCCTCACTTGCCTCAGTCTGGCTATACCAGCATTCTGGGTTTTTTGTTTTGTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTTGGGATGGAGTCTCACTCTGTCACCCAGGCTGGAGTGCAGTGA-CATGATCTTGGCTCACTGCAACCTCCATCTCCTGGGTTCAAATGATTCTTCTGCTTCAGCCTCTCAAGTAGCTGGGATTACAGGCACCCACCATCACACCCAGCTAATTTTTGTATTTTTGTAGAGATGAGGTTTTGCCATGTTGGCCAGGCTGGTCTCAAACTCTTGACCTCAGGTGATCTGCCCACCTCAGCCTCCCAAAGTGCTGGGATTACAGGTGTGAGCCACTGAGCCCAGTCTGTTTTGTTGTTTTTTGAGATGGAGTCTCACTCTGTCGCCCAGGCTGGAGTGCAGTGGTACAATTTTGTCTGACTGCAGCCTCCACCTCCTGAGTTTAAGAGATTCTCCTGCCTCAGCCACACAAGTAGCTGGGATTACAGGCGCGTGCCACCACATGCGTCTAATTTTGGTATTTTTAGTAGCGATGGGGTTTTGCCATATTGGCCAGGCTGGTCTCGAACTCCTGGCCTCAAGTGATCTGCACACCTCGGCCTCCTGAGTAGCTGGGATTACAGGCGTGAGCCACCATGCAGGGCCTTTCTGGTCTTTTAACGCACAAAGCTATTTCCCAGTTCTGGGTGTTTATAGTATCATTGCCAGTTCCTGGAAAGCTCTTTCCAGAAGCCTTCACATGACTGATCCCTTATCCTCCTTCAGGTCTTAGCTCAAATGCCTCCTTTTCAGAGAGCTCCTTCCTGACCATTTTATGCAATGTGCTTTCCTCTAGTTAGTCTCTCTTCATTCTGTGTATTTCCTTCAGAGCATTTATCATCATCTTGGTCCTGATGCTTGCTGGTTTACATGTTTGTTGTCTGTCTCCCACACAGAAAGCAAACCAGCCCTTCATCTGTCTTGTCCACCACTTTATCCCAGCACAGTGACTAACATATATCAGTAGTCAATCAATAAATAGCTATAAGCCAGGCACGGTGACTCACACCTGTGATCCCCGCACTTTGGGAGGCCAAGGTGGGCGGATCCTCTGAGGTCAGGAATTTGATATCAGCCTGCCCAACATGGCGAAACCCCGTCTCTACTAAAACTATAAAAATTAGTCGAGTGTGATGGCGTGCGCCTGTAATACCAGCTACTTGTGAGGCTGAGGCAGGAGAATCGCTTGAACCCGGGAGGCAGAGGTTGCAGTGAGCCGAGATCACACCACAGCACTCCAGCCTGGGTGACAGAGCAAGACCTTGTCTCAAAAAAATAAGAAATAGAAATATATATATGCTGCCACAAGAAATTCACTACTTTTTAGCAAAAAACACAGATTCCTAATTAAAGAAAGGGGAAACCTCTCTCTAAATAACTTCAGAATTCGGGGCAGAAAACGCTACATGTGGAAACTCGTCTTGAAAAACAGTCCCGTTTGTGAACAGGAAACACTTGGACTACACTTTTTCCATCTCCACGAAGGACTTAAATGTGCAGCATTGATGAAGAGGCAGTTAGCCCCAGTCCTTACCATTTCTGCATATTCCACCTGCTCCCCCTCATGGTACAGCTCTGGGGGCAGGTTATAAATTCGCAAGATGTTATCAGCACTATTGGTCAAGATGCAGGAACCGTCAGGAGCCCTAGAAACAGGGGAGAGTTAGAAAGCTGGCCAGACCTATGCTTTTCAAGTGTAGGGCTAGGGCTGAGCCTGCCTCTGGGGTAGGTAAGCCCCCCTGAATCCTTGAGGGAAGTAGAAGACACAAACTGCTAGATAAAATGTAAGCTCAGTCTAAAAGGGCTACGTGCCGCTTCTCCCAGCTCTGGGGCATCCCTCTCCTAGAAAACTGGACTGTTTTACAGTGAAAAT-CTCGGGGGTGGTCAGCTCCCTGCCCCGTTGTTATCCTTACCACTTACAGCCTTTCAAGAAGTTCTCAGGTTGGGTGCTGAACTCTGAC-CAGGAACCACTGAGAAATCGAGGCAGCTGGGAGAAG-CTGTAGTTCCAAGCGCTGAAAGGAAGATGGGGGACAATAAACCTGGGTCGCCAAGCAAAGGGGGCAGAGGCCTGGAGAAGTGGGTCTCAGGACCAGAGGACAGATCGACCTCACACTTCATCTCCCCAGACTCCACACTCCACTGCCATCACCACTTACG-TGTCTCCCTCGTCCTCTGCAGCGGGTTCCCCAGAGGTATCTTCCATGGCTTTTCCAGACCCCAACTCTGGCCCGTTCGCTTCTTCTTCAGAAAGGCTCCCGTTTGCTTCTTCTGCAGGAAGGCTTGTATTTTCAGAAAGTTCTTGCTCCTCGATTCGAGGACTCAACTCACTAGGGGAACCAAACTCTGTTTCCAGGGGAGTGGAGAGAGAAACTGGGTCCCCCTCCCGTAGCTCCTGGGACACAGCTGAGCCAGCCACAGGATCTGGGGACAACCGGGGCGGATCCCCCCTTTCGGGAGGCGGTGGCATCAGTTCAGAGTCCGCATTTTTATTCATCGGGGAAGCGTGGGGAGAAGGATGGGCTGGAGCTGGGTCCTGGTCTGA-AGGACAGCAGTCCGGAGCTAACGGTTGAGTCTCCAAAGTCTTCATACTGCAGAGGAAGCACAGCGGAGATTAGCCTCAGCCAGGATGGCTTCGAAGTTCTCAGGGATCCGACGCAGAGCTAAAGAAACCCACCTGTGCTTCCCTCCTCTTCTGGGAGTAGGCAGAAGACTCCCGGGAGGAGAGGCGAACAGCGGACGCCAATTCTTTTGAAAGCACTGTGTTCCTTAGCACCGCGGGTCGCTACGGGCCTCTTGCTGTCGCGGGATTTCGGTCCACCTTCCGATTGGGCCGCCGCATCCCGGATCAGATTTCGCGGGCGACCCACGGAACCCGCGGAGCCGGGACGTGAAAGGTTAGAAGGTTTCCCGTTCCCATCAAGCCCTAGGGCTCCTCGTGGCTGCTGGGAGTTGTAGTCTGAACGCTTCTATCTTGGCGAGA-AGCGCCTACGCTCCCCCTACCGAGTCCCGCGGTAATTCTTAAAGCACCTGCACCGCCCCCCCGCCGCCTGCAGAGGGCGCAGCAGGTCTTGCACCTCTTCTGCATCTCATTCTCCAGGCTTCAGACCTGTCTCCCTCATTCAAAAAATATTTATTATCGAGCTCTTACTTGCTACCCAGCACTGA
--CC-T--AAC-CCTAA----CC--CAT-A-AC-CC----TAAC----CCTA-A----CCTACC-CTA--ACC--CTAA----CCCTAACCCTAACCTA-A-------CCCTAACCCTAACC---CT-AACCCTAAC-CCTAACC-C---T-A---A-C--CCT-A---ACCCTAA-CCCT---A--AC---CCT-A-AC-CCTAACCCAACCCTAACCTAA---CCCTA----ACCCTA-AC---CCTAAACC---CTAACC---CT-AACCCTAAC-CCTAACC-C---TAACCCTAACC--CT-A---ACCCTAA-CCCT---A--AC---CCT-AACC-CTAACCCTAACCCT--A----ACCCTAACCCTAACCCT-AACC-CTAAC-C--C-----T--AAC-C-C-TAACC---C-TA-ACCCT-A-ACC-CTAA-CCC-TAACCCT---A-ACC---CT----A-A-C-C---CT-A--A-CCCTA-A-C--CCTAACC-CTAACCCTAA--CCCTAAC-C--CTAACCCTA-ACCCTAACCCTAACC-------CT---A-A--CC-CTAA--CC--CTAACCCTAACCCT-A---ACCCTAA-C-CCTAACCCT---A-AC---CCTAACCCTAACCCTA-A-----CC-CT-AACCCTAACC----CTA-A-CCCTA-ACCCTAACCCTAAC--CCTAAC--CCTAACCCTAAC-CCTAACC---C-T-AACCCTAAC-CC--TAACCCTA--ACCCT--AACCCT-A-AC-CCT--AAC-CCT-A-ACCCTAACCCT-A-ACC--CTAACCCTAAC---CCTAACCCTAAC-C--CT---AACCCTAACCCTAACCCTAAC-C-----CT-A-ACC-CTAA-CCC-TAACCCT---AACCCTA-ACC--C---T-AACCCT-A--A-CCCTA-A-C--CCTAACC-CTA-ACCCTAACCCTAACCCTA---ACCCTAACCCTAACCCTAAC----C---CTAAC-----CC--TAA--CC--CTAACCCTAACCCT-A---ACCCTAA-C-CCT-AA-CC-CTA---A-CCCTAACCCT-AACC---CTAAC-CC--T-AACCCTAACC----CTA-A-CCCTA-AC-C--CT---AACCCTAACCCTAAC-CCTAAC-CCT-A--ACCC---T-AAC-CCTAA-CCCTAACCC-T-A-ACCCTA-AC--CCTAAC--C-C-TAAC---CCT-A-ACC-C--TAACCCTAAC---CCT-A-AC--CCTA-ACCCTAACCCT---AACCCT-AACCCTAACCCTAACCCTAACCCTAACCCT-AACCCTAACCCT---A---ACCCTAAC-C-CT-AACC---CT--A--ACCCTAACCCTAACCCTAAC-C-CT--AACC-CTAAC-CCT---AAC-CCT-A-AC--C--C-T-AACC-CT-AA--CCCT---A--AC---C-CTAACCCT-A-A-CC--CTAA---CCCTA--ACCCTA-ACCCTAACCCTAACC---CTAACC---CT-AACCCTAAC-CCTAACC-C---T-AAC--CCTACC-C--TAACCCTAA-CCCT---A--AC---CCT-AACC-CT-AACCCTAACCCTAACCCT-AACCCT---A---ACCCTAACCCTAAC-CCTA-ACCCTA--ACCCT--AAC-CCTAACCCTAACCCTAACC-CTAAC-CCTAACCCT---A-A--C-CCTAAC-C--CTA-AC-CCTAAC----CCTA-A--C-CCT--AACC-C-TAACCCTAA---CCCTAACCCTA--A-CCCT-AACCCTAACCCTA---ACC---CT-AACCCTAAC-CCTAACC-C---T-AAC-CCTAACC-CTAAC-CCT-A--A-C----CCTA-A-CCCT-A---ACCCT--A--ACC---CT-AAC-CCTAAC-CCTAACCCTA-ACCCTAACCCT--AACCCTA-ACCCT-A-ACCCTAACCCT---AA-CCCTAACCCTAA-CCCTAACAACCCT-AACCC-TAACAACCCT-A--AC--AACCCTAA---C-CC---T-A-A-CCCT-AACCCTAACC--CTAACCCTA-ACCCTAACC-CTA---A--C-C-C-TAACCCTAACCCTAACCCT-A-A-CCCTAACCCTAACCCTAACCCTAACCCTAAC--CCTAACAACCCT-AACCCTAAC-CCTA-ACCCTAA-C--CCTAACCC-T-AAC---C--CT-AACC-C-TAACCCTAACCCTAACCCTAAC-CCTAACCCTA-ACCCT-AA-CCCTAACCCTAA-CC-CGAACCCTAACCCGAACC--CGA-ACCCGAAC---CCGA-ACC--CG-AACCCGAACC-C-GA--ACCCTAACCCGA-A-C--CC-G---AAC---CCG-AA-CCCG-AAC-CCT--AACCCGAACCCTAACCCGA-----A-CCCGAAC-CC-G--A-ACCCG-AAC--CCGAACCCGA---ACCCGAA-C-C-CGAACCC--GAACCCGA----ACCCT-AACCCCGA--AC-CC-C-GAACCCCAACC------CCA-ACCCCAACC----C-CAACCCCAACCCCAACCCCAA-CCCCA-A--C--CC-C----AA-CCCCAAC-CCTAACCCCTAACCCCA-A--CCCCA--ACCCCAACCCG-AA---C-C-C----GAAC--CCGAA--C----CCG--AAC-C--C-----G-AAC-C--C--G----A-A--CCC------GAACCCG-AAC-C--CGA--AC-C-----CCA--ACC-CG-A--ACCCCAA----CCCCA-ACCCCAA-CCCCA---A-CCCCAACCCCAACCCCAACCCCA-ACCCCAAC-CCGAACCC-CA----AC--C-C---GAACCCG-----AACCCG-AACCCG--A--A-CCCTA----ACCCGA-ACCCGAACC--C--GAACCC--G-AAC--CCTA-A-CCCG-AA-C---CCTAACC----C---T-AACCCTAACCCTAACCCTAACCCTAAC-C--------CTAA----CCCT-AA-CCCT-----AA-CCCTA-ACCCTTCCT-C-AG----CCTCTCAAC-CTG-CT---TGGGTTAC-AG--G--TAT--GAGC-C-CGGG--TGCCTAGCC-A-AACA-T--TCCATTTTATA-TGTATATGCT-AGGAATGAATA-ATCTCTAAACC-AAATTA---TGA-AAATT-CTACC-TTAAACAA-TAC-CA--AT---AGCAATATTAT-ACTTAGGAATAAATG-G-AAT-GA---AAC---GACAAGACT-TAGAT--GAG-G--G-AA--ATTAT--AAGAC-AT-TACTTAAG--G-AAATTAAA-CTTCCAG-TAAATGTAAAAAT--GTATC-TTATTTGTGGATTTGTAGACCACATTGTTAAGTTTCCCAAAGTACACAAAGCAAT-CCGT--GGA-TT-CGATGT-T--AT--T-C-CTACA--AAAAT-CCCAAAGG------CCTTGG-GACAGAAGTGGATAA-GCTGATCC--T-G-ATC-ACATC-CCAA--TTTCAAATT--TTATTACAAAGGAA--C-AGTA-ATAAAAACAG-T-GGGATCCTTG-CAC-AGGAATAAACAGA-AAGATCAACTGAA-T-TGAAT---TGGGAGTCCAGACAGAAA-ACAAT--ACCT-CTAT-GCTCAACTG--ATTTTAGACAAAGTC-CATTA-C-CAGTA-AATTGGGGAAGA---ATCCTGTCCTCAACAAGT-G-AT--G-T-A-AG---GCA-ACTTGCT-ATC----CA-CAT----A-AAGG--GAAATGAAATTGTATCCTTACCTCATACCACATAAAAAATTAACTTAC-GATG-G-AT-CGAAGAC--CA-A-AACAGGTGAA--A-A-C-TA-A--AAACTCTG-GAAGAAAACGT-ACAG-T-T-AAGCATTC-ATG-A-CCTTACATGTA-GCA-AT-AG-TT-TCT-TACATCT--GA-CA-CCA-AA-A-GCAC---A-GA-CCAC-AA-A-AGGA----AA----AAT-AAATCAATTTATTTCCT--CA----AAAT--TTAC--AACTTTTAC-GTCTC-AGA----AG---A-CAT--GA--AGAAAAAAG-TTGAAAGA-CA-AAAT---GTTATA-ATA-GGAA-AAAC--A-AC-TGTC-TTATA-G-TA-TA---CTCTC-AACAC-TCAA-CAC-AGAAC-ACT--T--CTGTTACCAG--ATA--C--ATGGGTT-T-T-TTCCCCACACAG-ACCAAATCT-TGGGTACC-AG--CTGC-GT--GTCCT--A-CA-GTGCA--ATCCAATTG-TGACAGTA-AATG-G-AG-A----AAGCA-----TCAG-A-C-C---CCACAGGC-T-A-A--TGGCTCAGTC---CTAGGAATACACGTCAT-G-CCCCTT-GTTGCT-TGCA-AATTTA
Score: -1685



"""
