from pathlib import Path
import argparse
from Bio import SeqIO


# ===================== Matrix initiation =========================================

def init_score_matrix_local(m: int, n: int):
    # matrice (m+1) x (n+1) inițializată cu 0
    return [[0] * (n + 1) for _ in range(m + 1)]



def score_cell_local(score, i: int, j: int, a: str, b: str, match: int, mismatch: int, gap: int):
    diag = score[i - 1][j - 1] + (match if a == b else mismatch)
    up   = score[i - 1][j] + gap
    left = score[i][j - 1] + gap
    return max(0, diag, up, left)



def smith_waterman(seq1: str, seq2: str, match=3, mismatch=-3, gap=-2):
    # Implementare simplificată Smith–Waterman.
    m, n = len(seq1), len(seq2)

    # Inițializare matrice
    score = init_score_matrix_local(m, n)

    max_score = 0
    max_pos = (0, 0)

    # Umplem matricea celulă cu celulă
    # + memorăm cea mai mare valoare și poziția asociată
    for i in range(1, m + 1):
        ai = seq1[i - 1]
        for j in range(1, n + 1):
            bj = seq2[j - 1]
            score[i][j] = score_cell_local(score, i, j, ai, bj, match, mismatch, gap)

            if score[i][j] > max_score:
                max_score = score[i][j]
                max_pos = (i, j)

    # ================== Backtracking ==================
    # pornim din celula cu scor maxim și mergem înapoi
    align1, align2 = "", ""
    i, j = max_pos
    while i > 0 and j > 0 and score[i][j] > 0:
        # recalculăm scorurile vecinilor pentru a decide direcția
        diag = score[i - 1][j - 1] + (match if seq1[i - 1] == seq2[j - 1] else mismatch)
        up   = score[i - 1][j] + gap
        left = score[i][j - 1] + gap

        if score[i][j] == diag:
            align1 = seq1[i - 1] + align1
            align2 = seq2[j - 1] + align2
            i -= 1; j -= 1
        elif score[i][j] == up:
            align1 = seq1[i - 1] + align1
            align2 = "-" + align2
            i -= 1
        else:  # stânga
            align1 = "-" + align1
            align2 = seq2[j - 1] + align2
            j -= 1

    return align1, align2, max_score


def load_two_sequences(fasta_path: Path, i1: int, i2: int):
    """
    Încărcăm FASTA și alegem două secvențe după index.
    """
    recs = list(SeqIO.parse(str(fasta_path), "fasta"))
    if len(recs) < 2:
        raise SystemExit("[eroare] Fișierul trebuie să conțină cel puțin 2 secvențe.")
    if not (0 <= i1 < len(recs) and 0 <= i2 < len(recs)):
        raise SystemExit(f"[eroare] Indici invalizi (0..{len(recs)-1}).")
    return str(recs[i1].seq), str(recs[i2].seq), recs[i1].id, recs[i2].id


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fasta", required=True, help="Cale către FASTA-ul propriu din data/work/<handle>/lab01/")
    ap.add_argument("--i1", type=int, default=0, help="Index prima secvență (implicit 0)")
    ap.add_argument("--i2", type=int, default=1, help="Index a doua secvență (implicit 1)")
    args = ap.parse_args()

    fasta_path = Path(args.fasta)
    if not fasta_path.exists():
        raise SystemExit(f"[eroare] Nu găsesc fișierul: {fasta_path}")

    s1, s2, id1, id2 = load_two_sequences(fasta_path, args.i1, args.i2)
    a1, a2, sc = smith_waterman(s1, s2)

    print("=== Aliniere locală (SW) ===")
    print(f"{id1}  vs  {id2}")
    print(a1)
    print(a2)
    print("Score:", sc)


if __name__ == "__main__":
    main()

"""

=== Aliniere locală (SW) ===
NG_017013.2  vs  NC_060941.1
CTCGAACTCCTGACCTCAGGTGATCC--A-CCT--GCCTCAGCCT--CCCAAAGTGCTGGGATTA--C-AGGAGTCAGCC--ACCGC--ACCC-AGCCCCAA--CTAATTTTTGTATTTGA--GTAGAGACAGGGTTTTACCATGTTGGCCAGGCT-GGTCTAA----AACTCTTCACCTCAGGTGATCC--ACCC--A-TCTCAGCCT--CCCAAAGTGTTGGGATTACAGGCGTGAGCC--ACCGT--GCCTGGCCCTGGATTTCACTCTTGCCC--ACCCATAAACCATTCACTCTTCTGTTTTAA----AACTCTCTTGGCCGGGCGCAGTGGCTCATGCCTGTAATCCC-AGCACTTTGGGAGGCC-AA-GGTGGGCAGATCAC-AA-GGTCAGGAGTTCGAGA-CC-AGCCT-GGCC-AA---TATGA---TGAACCC---CCC-ATCTCT-A--CTAA----AA----AA--AT-A--C-AA----AA----AA-ATTAGCCGGGTGTGGTGGCACATGCCTGTAATCCC--A-GCT-ACTCGGAAGGTTGAGGC-AGGA---GAATCACTTAAACCTGGGAGGCGGAGGTTGCGGTGA-GCTGAGATGGTGCCACTGCACTCC--AGCCTGGA--C-AA--C-AGA-GCAAGACTCTGTCTCAA-AC-AA-AC-AA-AC-AAAAAAAACCTCT--CTCATGGCCTGGCATGGTGGCTCACGCCTGTAATCCTAGCACTTTGGAAGGCTGAGGCAGGTGGATCACCTGA-GGTCAGGAGTTTGAGA-CC--AGCC-AGGCC-AA-CGTGGCAA-AA-CCTGTCTCTACTAA-AA--AT-ACAA----AA-ATTAAGCC-AGGCGCGGTGGCTCATGCCT-A---TAATCCC-AGCACTTTGGGAGGCCGAGACCGGCGGATCAAATGTCAGGA--GT-A--CGAGA-CC--ATCCT-GGCC-AA---T-ATGGTAA-AACCCCGT--CTCT-A-TTTAA-AAAAATACAAAAATTAGCTGGGCATGGTGGCGGGTGCCTGTAATCCC--A-GCT-ACTCGGGAGGCTGAGGC-AGGA---GAATCGCTTGAATCC-AGGAGGCAGAGGTTGCAGTGAGCCGAGATCACG--CCATTGCACTCC-AGCCTGGGCG-A-CAGAGCAAG-ACTCGTCTCAA----AA----AA--AAAAAAAAAACACCT--CTCTC-ATGA--CT-TCCC-AA----ATA----AACTCCAAATGCCTTACCC-ATA--AGAA-CC-AACACG-ACGTG-GCTGCTCT-TCTCTG-TCCTC--ACCCC-TCTGTCCC--CCTC-ACTTGCCTCAGTCTGGCTATACCAGCATTCTGGGTTTTTTGTTTTGTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTTGGGATGGAGTCTC-ACTCTGTC-ACCCAGGCTGGAGTGCAGTGA-CATGATCTTGGCTCACTGCAACCTCCATCTCCTGGGTTCAA-ATGATTCTTCTG--CTTC-AGCCTCTCAA---GTAGCTGGGATTACAGGCACCC--ACCATC-ACACCCAGCTAATTTTTGTATTTTTGTA-GAGATGAGGTTTTGCCATGTTGGCCAGGCTGGTCTCAAACTCTTGACCTCAGGTGATCTGCCC-ACCTCAGCCTCCCAAAGTGCTGGGATTA---CAGGTGTGAGCCACTGAGCCC-AGTCTGTTTTGTTGTTTTTTGAGA-TGGAGTCTC--ACTCTGTCG--CCC-AGGCTGGAGTGCAGTGGTA--C-AATTTTGTCTGA--CTGCAGCCT---CC--A-CCT---CCTGAGTTTAA---GAGATTCTCCTGCCTCAGCCACACAA-GTAGC-TGGGATTAC----A-G-G--CGCGTGCC-A-CC--ACATGCGTCTAATTTTGGTATTTTTA-G-TAGCG-ATGGGGTTTTGC-CATATTGGCCAGGCTGGTCTCG-AACTCCTGGCC-T---CAAGTGATCTGCACACCTCGGC-CTCCTGAGTAGC-TGGGATTACAGGCGTGAGCCACCATGCAGGGCCTTTCTGGTCTTTTAACGCACAAAGCTATTTCCCAGTTCTG-GGTG--TTTAT-AGTATCATTGCCAGTTCCTGGAAAGCT---CTTTCCAG--AA-GCCTTCACATGACTGATCCCTTATCCTCCT-TCAGG-TCTTAGCTCAAATGCCTCCTT-TTCAGAGAGCTCCTT-CC--TG-AC-CATTTTATGCAAT--GTGCTTTCCTCTAGTTAGTCTCTCTTC----AT-TC--TGTGTATTTCCTT----CAG-AGCATTTATCATCATCTTGGTCCTGAT-GCTTGCTGGTTT-ACATGTTTGTTGTC--TGTCTCCCACACAG-AA-AGCAAACCAGCCCT-TCATCTGTCTTGTCCACCA-CTTTATCCCAGCACAG-T-GACT-AACAT-ATATCAGTAGT-CA-ATC--AATA-AATAGCTATAAGC-CAGGCAC-G---GT-GACTCACA--CC-TGTGATCCCCGCACTTTGGGAGGCCAAG-GTGGGCGGATCCT---C---TGAGGTCAGG-AATTTGATAT-CAGCCTGCCCAACATGGCG-AA--ACCCCGTCT-C-TA-CT-A-A-AAC-TATAAAAATT-A-GT-CGAGTGTGATGGCG-TG-CGC----C-TGT-AATACCAGCT----ACT-TGTGAGGCTGAGGCAGGAGAATCGCTTGAACCCGGGAGGCAGAGGTTGCAGTGAGCC-GAGAT-CA-CACCACAG---C--AC-TC---CAGCCTGGGTGACAGAGCA-AGACCTTGTCTCAAAA--AAATAAGAAATAGAAATATATATATGCTGCCACAAGAAATTCACTACTTTTTA-G-CAAAAAACACAGATTCCTAATTAAAGAAAGGGGAAACCTCTCTCTAAATAACTTCAGAATTCGGGGCAGAA-AAC-G-C-TACATGTGGAAACTCGTCTTGA-A---AA-ACAG-TCCCGTT-TGTGAACAGGAAACACTTGGACTACACTTTTTCCATCTC-CACGAAGGACTTAAATGTGCAGCATTGATGAAG-AGGCAGTTAGCCCCAGTCCTTACCATTTCTGCATATTCCACCTGCTCCCCCTCATGGTACAGCTCTGGGGGCAGGTTATAA--ATTCGCAAGATGTTATCAGCACTATTGG-TCAAGATGC-AGG-A-AC-CGTCAGGAGCCCT
CT--AAC-CCTAACC-C---TAACCCTAACCCTAACCCTAACCCTAACCCTAA-CCCT---A--ACCCTA--A--C--CCTAACC-CTAACCCTAACCCTAACCCTAA---CCCTA----ACCCT--A-AC----CCTAACC---CTAACC---CTAACCCTAACCCTAAC-CCTAACC-C---TAACCCTAACCCTAACCCTAACCCTAACCCTAA-CCCT---A--AC---CCTAACCCTAACCCTAACCCTAACCCT--A----ACCCTAACCCTAACCC-T-AACC-CTAAC-C--C-----TAACCCTAAC-C-C-TAACC---C-TA-ACCCT-A-ACC-CTAA-CCCTA--ACCCT---AACCCTAACCCT----A-A-CCCTAACCCT-A--A-CCCTA-ACCCTACCCTAACCCTAACCCTA--ACCCT-AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC-------CT---A-A--CC-CTAA-CCCTAACCCTAAC-CCTAACCCTAACCCTA--ACCCTAA-C-CCTAACCCT---A-AC---CCTAACCCTAACCCT-A-A-----CC-CT-AAC-CCTAACCCT-AACCCTAACCCTA-ACCCTA-AC-C---CT-AACCCTAACCCTAACCCTAACCCTAACC-CTAAC-CCTAACC---C-T-AACCCTAAC-CC--TAACCCTA--ACCCT--AACCCT-A-AC-CCT--AAC-CCTAACCCT-A--ACCCT-A-ACCCTAACCCTAACCCTAACCCT---AACAACCCTAAC-C--CTAACAACCCTAACAACCCTAACCCTAACCCTA-AC-C-----CT-AACCCTAACCCTAA-CCCTA--ACCCT---AACCCTA-ACC--C---T-AACCCT-A--ACCCTAACCCTA-ACCCTAACCCTAACCCTAACCCTAACCCTAACAA-CCC-TAACCCTAACCCTAACCCTAACCCTAACCCTAAC----C---CTAAC-----CC--TAA-CCCTAACCCTAAC-CCTAACCCTAACCCTA--ACCCTAA-C-CCT-AACCCTA--A-CCCGA----ACCCTAACCCGA-A-CCCGAACC--CGAAC-CCGAACC----CGAACCCGAACCCGAAC-C--CT-AACCCGAACCCGAACCCGAACCCGAAC-CCTAAC-C-CGA--ACCCTAACCCGAACCCGA-ACCCGAAC-CCGAA-CCCGAACCCGA-ACCCGAACCCGAACCCGAACCCGAAC--C-CTAACCCCGAACCCCGAACCCCAAC---CCCAACCCCAAC---CC-CA-AC--CCCA-ACC--C---C---------------------------------------------------------A---A-CCCCAAC-C--CCAACCC---C--AACCCCA---ACCCT-AAC--CCCTAACCCCAACC-CCAAC-CC------CAACCCGA-AC--CCGAAC-CCGAACC-C-GAACCCG-AAC-CCGA--ACCCGAACCCGAACC--CGA-ACCC--C-AA--CCCG-A-------ACCCCA--A-----CCCCA---ACCCCA-AC----C-CCAAC-CCCAACCCCA----A-C--CCCAACCCCA-AC-CCC-AA---C-CCGA--ACCCCA-ACCCGAACC-C-GAACCCGAACCCG---AACCCTAACCCGA-ACCCGA-ACCCGAAC-C---CGAACCCTA-ACCCGA--ACCCT--AACCCTAA----CCCTAACCCT-AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA-A--C-CCTTCCTCAGCCTCTCAACCT-GCTTGGG-TTACAGGTATGAGCCCGGGTGCCTAGCCAAACAT---TC-CATTTT-ATATGTATATGCTAG-GAAT-GAATAAT-CTC-TA--AACCA-AAT--TAT-GAAAATTCT-ACCTTAAACAA-T-A-C--CA-A--T-AGCAAT-ATTA-TA-CTTAGGAATA-A---ATG-G--A--ATG-A------------------AACG-AC-AAG--ACTT---AG--ATGAGG-GAAATTATAAG-A-CATT---ACTT-AAGGAAA-TTAAAC-TTCCAGTAAATG--TAAAAATG--T-AT--CTTAT--T--TGT--GGAT-TT-G-T-AGA--CCACATTGTT---A-AG-T--TTCCCAAAGTACACA----AAGCAATCCGTGGATT-CGAT-GTTA-T-TC-CTACAAAAATCCCAAAG-G-----CCTTGGGACAGAAG--TGGAT-A--AGC-TGATCCTGATCACATCCCAATTTCAAAT-TTTATT-ACAAAG-----GA-ACAGTAATA--AAAACAG---TGGGATC---CTTG--CA-CAGGAATA-AACAG-AAAGATCAACTGAA-TTGA-ATTGGGAGTCCAGA-CAGAAAACAATACCTCTATGCTCA---ACTGATTTTAGA--CAAAGTCCAT-T-A--CCAGTAAATT-GG-GG--AAGAAT--CCTG-TCCTCAACAAGTGATGTAAGGCAACTTGCTATCCA-CAT----AA-A-GG-GAAATGAAATTGTATCCTTACCTCATACCACATA-AAAAATTAACTTACGA-TG-GAT--CGAAGAC-CAAAACAGGTGAA-A--A-CTAAAAACTCTG-GA-----A-G-A--A-AA-CG--T--A-CAGTTAAGC--A--TT-CA-TGA-CCTTACATGTAGCA--ATAGTTTCTTACATCTGACA-CC------A-AAAGCACAGA-C----CACAAAAGGAAA-AATAAAT--CAAT-T-TAT-T--T-CCTC-A-AAATTTACAAC-TTTTACGTCTCAGAAGAC--A-T--GAA-GAAA-AAAGTTGAAA-----GAC-AAA-ATGTT-ATAA-T--AGGAAAAACAACTGTCTTATA-GT--ATACTC-TC--AACACTCAACACAGAACAC-TTCTGTTACCA-GATACA--TGG-GT----TTTTTCC--C-CACAC--A-GAC-CAAA--T----C-TTG--G--GTA-CCAGCT-G--CGTGTCC-TA-CA---GTGCA-A-TCCAATTG-T----GACA--GTA-A---AT---GG-A-G--A-AAGCA-T--C-AGACCCCA-CAG-GCTAATGGCTC-AG-TCCTAGGAATACACGTCATG-CCCCT
Score: 941

"""